# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0004_auto_20170414_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tipo',
            field=models.CharField(choices=[('AC', 'Assembléia de Circuito'), ('AE', 'Assembléia Especial'), ('CR', 'Congresso Regional')], max_length=2, verbose_name='Tipo'),
        ),
    ]
