# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0008_eventos_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregacao',
            options={'verbose_name_plural': 'Congregação'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.CharField(blank=True, max_length=50, verbose_name='Local do Evento'),
        ),
    ]
