# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0009_auto_20170601_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='owner',
            new_name='usuario',
        ),
    ]
