# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0010_auto_20170601_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=4, verbose_name='Sigla')),
                ('parte', models.CharField(max_length=1, verbose_name='Sigla')),
            ],
        ),
    ]
