# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0011_circuito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuito',
            options={'verbose_name_plural': '01 - Circuito'},
        ),
        migrations.AlterModelOptions(
            name='congregacao',
            options={'verbose_name_plural': '03 - Congregação'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': '02 - Eventos'},
        ),
        migrations.AddField(
            model_name='circuito',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='circuito',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
