# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0012_auto_20170601_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='parte',
            field=models.CharField(max_length=1, verbose_name='Parte'),
        ),
    ]
