# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ionibus', '0017_auto_20170601_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuito',
            options={'verbose_name_plural': 'Circuito'},
        ),
        migrations.AlterModelOptions(
            name='congregacao',
            options={'verbose_name_plural': 'Congregação'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='circuito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='congregacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ionibus.Eventos'),
        ),
    ]
