# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0019_auto_20170601_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name_plural': 'Responsável'},
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='id_congregacao',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='congregacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ionibus.Congregacao'),
        ),
    ]
