# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0020_auto_20170601_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='status_evento',
            field=models.CharField(blank=True, choices=[('01', 'Aberto'), ('02', 'Encerrado')], default='01', max_length=50, verbose_name='Status do Evento'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='tipo',
            field=models.CharField(choices=[('EG', 'Encarregado Geral'), ('EC', 'Encarregado da Congregação'), ('EE', 'Encarregado do Evento'), ('AC', 'Ajudante da Congregação'), ('AE', 'Ajudante do Evento')], max_length=2, verbose_name='Tipo'),
        ),
    ]
