# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0023_auto_20170601_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregacao',
            name='encarregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_EncarregadoCong', to='ionibus.Responsavel'),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_CircuitoCong', to='ionibus.Circuito'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_CircuitoEven', to='ionibus.Circuito'),
        ),
    ]
