# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0024_auto_20170601_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitao',
            options={'verbose_name_plural': 'Capitão'},
        ),
        migrations.AlterModelOptions(
            name='passageiro',
            options={'verbose_name_plural': 'Passageiro'},
        ),
        migrations.RemoveField(
            model_name='capitao',
            name='id_congregacao',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='id_capitao',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='id_congregacao',
        ),
        migrations.AddField(
            model_name='capitao',
            name='congregacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cong_Capitao', to='ionibus.Congregacao'),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='capitao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cap_Passageiro', to='ionibus.Congregacao'),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='congregacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cong_Passageiro', to='ionibus.Congregacao'),
        ),
        migrations.AlterField(
            model_name='capitao',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='capitao',
            name='telefone2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='crianca_colo',
            field=models.CharField(default='N', max_length=1, verbose_name='Criança de Colo'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='congregacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cong_Responsavel', to='ionibus.Congregacao'),
        ),
    ]
