# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0025_auto_20170602_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_resp_Capitao', to='ionibus.Responsavel'),
        ),
        migrations.AddField(
            model_name='congregacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='crianca_colo',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Criança de Colo'),
        ),
    ]
