# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0027_auto_20170602_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregacao',
            name='encarregado',
        ),
    ]
