# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0028_remove_congregacao_encarregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiro',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
