# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0030_auto_20170602_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='observacao',
        ),
    ]
