# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0031_remove_passageiro_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_passageiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='Data do Evento')),
                ('endereco_primeira_parada', models.CharField(max_length=200, verbose_name='Endereço')),
                ('endereco_segunda_parada', models.CharField(max_length=200, verbose_name='Endereço')),
                ('endereco_terceira_parada', models.CharField(max_length=200, verbose_name='Endereço')),
                ('pago', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Pago')),
                ('capitao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cap_lista_passageiros', to='ionibus.Capitao')),
                ('congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cong_lista_passageiros', to='ionibus.Congregacao')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_eve_lista_passageiros', to='ionibus.Eventos')),
            ],
            options={
                'verbose_name_plural': 'Lista de Passageiros',
            },
        ),
        migrations.CreateModel(
            name='Onibus_assentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_onibus', models.IntegerField(verbose_name='Qt. Ônibus')),
                ('qt_assentos', models.IntegerField(verbose_name='Qt. Assentos')),
                ('valor_passagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qt. Assentos')),
                ('congregacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cong_onibus_assentos', to='ionibus.Congregacao')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_eve_onibus_assentos', to='ionibus.Eventos')),
            ],
            options={
                'verbose_name_plural': 'Ônibus Assentos',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pgto', models.DateField(blank=True, null=True, verbose_name='Data do Pagto')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qt. Pago')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_lista_pagamentos', to='ionibus.Lista_passageiros')),
            ],
        ),
        migrations.AddField(
            model_name='lista_passageiros',
            name='onibus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_onibus_a_lista_passageiros', to='ionibus.Onibus_assentos'),
        ),
        migrations.AddField(
            model_name='lista_passageiros',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_passa_lista_passageiros', to='ionibus.Passageiro'),
        ),
    ]
