# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0033_auto_20170610_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_passageiros',
            name='evento',
        ),
    ]
