# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0035_auto_20170610_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data_evento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Evento'),
        ),
    ]
