# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionibus', '0036_auto_20170610_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_passageiros',
            name='endereco_primeira_parada',
            field=models.CharField(max_length=200, verbose_name='Primeira parada'),
        ),
        migrations.AlterField(
            model_name='lista_passageiros',
            name='endereco_segunda_parada',
            field=models.CharField(max_length=200, verbose_name='Segunda parada'),
        ),
        migrations.AlterField(
            model_name='lista_passageiros',
            name='endereco_terceira_parada',
            field=models.CharField(max_length=200, verbose_name='Terceira parada'),
        ),
    ]
