# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventosTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AC', 'Assembléia de Circuito'), ('AE', 'Assembléia Especial'), ('CR', 'Congresso Regional')], max_length=2, verbose_name='Tipo')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='Data do Evento')),
                ('circuito', models.CharField(blank=True, choices=[('CE01', 'CE01'), ('CE02', 'CE02'), ('CE03', 'CE03'), ('CE04', 'CE04'), ('CE05', 'CE05'), ('CE06', 'CE06'), ('CE07', 'CE07'), ('CE08', 'CE08'), ('CE09', 'CE09'), ('CE10', 'CE10'), ('CE11', 'CE11'), ('CE12', 'CE12'), ('CE13', 'CE13'), ('CE14', 'CE14'), ('CE15', 'CE15'), ('CE16', 'CE16'), ('CE17', 'CE17'), ('CE18', 'CE18')], max_length=4, verbose_name='Circuito')),
                ('parte', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Parte')),
                ('texto_base', models.CharField(blank=True, max_length=30, verbose_name='Texto Base')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
