# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventosTask',
        ),
    ]
